services:
  iombian-button-handler:
    image: iombian-button-handler
    container_name: iombian-button-handler
    privileged: true
    restart: unless-stopped
    ports:
      - ${BUTTON_EVENTS_PORT:-5556}:5556
    environment:
      BUTTON_PIN: ${BUTTON_PIN:-3}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    networks:
      - iombian-internal-services 

networks:
  iombian-internal-services:
    external: true
