services:
  iombian-button-handler:
    image: iombian-button-handler
    container_name: iombian-button-handler
    privileged: true
    restart: unless-stopped
    ports:
      - ${BUTTON_EVENTS_PORT:-5556}:5556
    environment:
      BUTTON_PIN: ${BUTTON_PIN:-3}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    networks:
      - iombian-internal-services 
    labels:
      com.iombian-button-handler.env.BUTTON_EVENTS_PORT.description: "Port for communicating button events."
      com.iombian-button-handler.env.BUTTON_EVENTS_PORT.type: "integer"
      com.iombian-button-handler.env.BUTTON_EVENTS_PORT.default: 5556

      com.iombian-button-handler.env.BUTTON_PIN.description: "The pin of the raspberry button."
      com.iombian-button-handler.env.BUTTON_PIN.type: "integer"
      com.iombian-button-handler.env.BUTTON_PIN.default: 3

      com.iombian-button-handler.env.LOG_LEVEL.description: "Log level for the python logger (INFO, DEBUG, ...)."
      com.iombian-button-handler.env.LOG_LEVEL.type: "string"
      com.iombian-button-handler.env.LOG_LEVEL.default: "INFO"

networks:
  iombian-internal-services:
    external: true
