name: Build
on:
  workflow_dispatch
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'

permissions: 
  packages: write

jobs:
  build:
    runs-on: obuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: image_metadata # you'll use this in the next step
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            iombian-button-handler
          # Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          tags: ${{ steps.image_metadata.outputs.tags }}
          labels: ${{ steps.image_metadata.outputs.labels }}
